name: Automatically check if an update is available and create a release if so
run-name: Automatically check if an update is available and create a release if so
on:
  push: null
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run rust app
    outputs:
      cdn_url: ${{ steps.get_cdn_url.outputs.CDN_URL }}
    steps:
      - name: retrieve or update cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: get cdn url and remove the quotes
        run: |
          CDN_URL=$(cargo run --release | head -n 1)
          CDN_URL=$(echo $CDN_URL | tr -d '"')
          echo $CDN_URL
          echo "CDN_URL=$CDN_URL" >> $GITHUB_OUTPUT
        id: get_cdn_url
  check-for-updates:
    needs: [build]
    runs-on: ubuntu-latest
    name: Check for updates
    env:
      CDN_URL: ${{ needs.build.outputs.cdn_url }}
    steps:
      - name: extract the version
        run: |
          VERSION=$(echo $CDN_URL | awk -F'/' '{print $4}')
          echo "The current version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        id: get_version
      - name: check if github release with the given version exists
        uses: actions/github-script@v4
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = "${{ steps.get_version.outputs.version }}";
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const release = releases.find((release) => release.tag_name === version);
            if (release) {
              console.log(`Release ${version} already exists`);
              core.setOutput("release_exists", true);
            }
            core.setOutput("release_exists", false);
      - name: download client binaries 'PathOfExile.exe', 'PathOfExile_x64.exe', 'Client.exe'
        if: steps.get_version.outputs.release_exists != 'true'
        run: |
          URL="${CDN_URL}PathOfExile.exe"
          echo "downloading $URL"
          wget -q -O PathOfExile.exe $URL
          
          URL="${CDN_URL}PathOfExile_x64.exe"
          echo "downloading $URL"
          wget -q -O PathOfExile_x64.exe $URL
          
          URL="${CDN_URL}Client.exe"
          echo "downloading $URL"
          wget -q -O Client.exe $URL
      - name: create github release and attach the files
        if: steps.get_version.outputs.release_exists != 'true'
        uses: actions/github-script@v4
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = "${{ steps.get_version.outputs.version }}";
            const { data: release } = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: version,
              name: version,
              body: `Release ${version}`,
              draft: false,
              prerelease: false,
            });
            const { data: upload } = await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              name: 'PathOfExile.exe',
              data: require('fs').readFileSync('./PathOfExile.exe'),
            });
            const { data: upload2 } = await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              name: 'PathOfExile_x64.exe',
              data: require('fs').readFileSync('./PathOfExile_x64.exe'),
            });
            const { data: upload3 } = await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              name: 'Client.exe',
              data: require('fs').readFileSync('./Client.exe'),
            });
            core.setOutput("release_id", release.id)